create table vehicles (
    id bigint generated by default as identity primary key,
    brand text not null,
    model text not null,
    year int not null,
    category text not null check (category in ('Sedan', 'SUV', 'Luxury', 'Hatchback', 'Electric')),
    daily_rate numeric(10, 2) not null check (daily_rate > 0),
    fuel_type text not null,
    seating_capacity int not null default 5,
    status text not null default 'available' check (status in ('available', 'rented', 'maintenance')),
    created_at timestamp with time zone default now()
);

create table rentals (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    vehicle_id bigint references vehicles(id) on delete restrict,
    customer_name text not null,
    customer_email text not null,
    start_date date not null,
    end_date date not null,
    total_cost numeric(10, 2) not null,
    status text not null default 'booked' check (status in ('booked', 'active', 'completed', 'cancelled')),
    created_at timestamp with time zone default now(),
    constraint valid_date_range check (end_date >= start_date)
);

insert into vehicles (brand, model, year, category, daily_rate, fuel_type, seating_capacity)
values
('Toyota', 'Camry', 2024, 'Sedan', 3000, 'Petrol', 5),
('Mahindra', 'XUV700', 2024, 'SUV', 4200, 'Diesel', 7),
('Tesla', 'Model 3', 2024, 'Electric', 4500, 'EV', 5);
